# Generated by Django 3.2.9 on 2021-12-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211201_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорие', 'verbose_name_plural': 'Категория'},
        ),
    ]
